# Generated by Django 4.1.3 on 2022-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_auto', models.CharField(max_length=50)),
                ('ruedas', models.CharField(max_length=2)),
                ('puertas', models.CharField(max_length=2)),
                ('patente', models.CharField(max_length=10)),
                ('dueño_auto', models.CharField(max_length=50)),
                ('rut_dueño', models.CharField(max_length=10)),
            ],
        ),
    ]
