# Generated by Django 4.1.3 on 2022-12-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('apellidoP_cliente', models.CharField(max_length=20)),
                ('apellidoM_cliente', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(max_length=20)),
                ('apellido_parterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=20)),
                ('seccion', models.CharField(max_length=20)),
            ],
        ),
    ]
