# Generated by Django 4.1.4 on 2022-12-26 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0002_cliente_personalrrhh'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='marca_auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.auto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.personalrrhh'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
